### ISSUE TITLE
remove events page?

### ISSUE THREAD

**Issue by vpnagraj** [uvarc/rc-website#12]
we haven't consistently had events to curate on the [events page](https://staging.somrc.virginia.edu/education/events/) ... so it's been "check back soon" for several months now

should we remove this page altogether? at least until we have consistent outreach events / some way to pull in events from elsewhere?

**Comment by nmagee** [comment]
I just thought about that while editing it a little bit. I sort of like the idea of the page -- it's not a workshop or a formal class we're teaching, it's how we integrate with the outside world.

But yeah, we could always hide it for now, until we have more consistent events?

**Comment by vpnagraj** [comment]
removed ... at least from menu for now
