### ISSUE TITLE
Removing snap-stanford version 5.0.9-py3.6

### ISSUE THREAD

**Issue by hcars** [uvarc/rc-website#205]
Hi all,

One of the net.science back-end codes is currently relying on version 5.0 of this library. Can you please keep this on here a while longer until we have upgraded our work to SNAP 6.0?

**Comment by rsdmse** [comment]
Thanks for your feedback. We will still have `5.0-py2.7` in addition to `6.0.0-py3.8`. If you need version `5.0.9` with Python 3, does the Python minor version matter to you? If not, we could install `5.0.9-py3.8` that uses Python 3.8.8.

**Comment by hcars** [comment]
I need Python version >=3.6. So that should be fine. Thanks.

**Comment by rsdmse** [comment]
Great. I have added the `snap-stanford/5.0.9-py3.8` module. This will be available to users after maintenance. Please note that `6.0.0-py3.8` will become the new default so remember to specify the module version when you load it.
```
$ module load snap-stanford/5.0.9-py3.8
$ python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snap
>>>
```

The table has been updated too.

**Comment by hcars** [comment]
@rsdmse I think we will be up to SNAP 6.0.0 soon on aforementioned software. I will tell you if and when we will permanently move away from SNAP 5.

**Comment by rsdmse** [comment]
Thanks for the note. We'll keep the module for the next cycle so no rush.
